// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6E824ODTtDDk37vjAwo86YfACdt9iRE',
    appId: '1:743902549930:web:04d8f9d073d2948571bdd3',
    messagingSenderId: '743902549930',
    projectId: 'basic-crud-app-e2013',
    authDomain: 'basic-crud-app-e2013.firebaseapp.com',
    storageBucket: 'basic-crud-app-e2013.firebasestorage.app',
    measurementId: 'G-8KDG2ZE9JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xFIIpdPFZ0aPiXAaJUiYXC3sOM4xJgI',
    appId: '1:743902549930:android:126b64a01e188f0a71bdd3',
    messagingSenderId: '743902549930',
    projectId: 'basic-crud-app-e2013',
    storageBucket: 'basic-crud-app-e2013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQTddc7g2zIoTXQuacryKAigWxfOvQ5uM',
    appId: '1:743902549930:ios:60ffd06aa44fbb5d71bdd3',
    messagingSenderId: '743902549930',
    projectId: 'basic-crud-app-e2013',
    storageBucket: 'basic-crud-app-e2013.firebasestorage.app',
    iosBundleId: 'com.example.basicCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQTddc7g2zIoTXQuacryKAigWxfOvQ5uM',
    appId: '1:743902549930:ios:60ffd06aa44fbb5d71bdd3',
    messagingSenderId: '743902549930',
    projectId: 'basic-crud-app-e2013',
    storageBucket: 'basic-crud-app-e2013.firebasestorage.app',
    iosBundleId: 'com.example.basicCrudApp',
  );
}
